# Generated by Django 5.2.6 on 2025-11-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_module_image_url_profile_is_premium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='image_url',
            field=models.URLField(blank=True, help_text='Enter the image URL for this module', null=True),
        ),
    ]
