# Generated by Django 5.2.6 on 2025-11-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_module_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for this module.', null=True, upload_to='modules/'),
        ),
        migrations.AddField(
            model_name='module',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Check if this module requires premium access.'),
        ),
        migrations.AlterField(
            model_name='module',
            name='image_url',
            field=models.URLField(blank=True, help_text='OR enter an external image URL for this module.', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Grant premium access to this user.'),
        ),
    ]
